services:
  bot:
    build:
      context: . # где находится Dockerfile
      dockerfile: Dockerfile # Явно указываем Dockerfile
    image: bot_secure_trains:v1
    container_name: bot_secure_trains
    environment:
      - PYTHONUNBUFFERED=1 # Для отображения логов в реальном времени
    volumes:
      - /proj/bot_secure_trains:/proj/bot_secure_trains
    restart: unless-stopped
